services:

  app:
    build: .
    container_name: card-processing-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ogabek2006
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: your-very-secret-key-minimum-32-characters-long
      JWT_EXPIRATION: 86400000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: card-processing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ogabek2006  # ← shu yerda
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: card-processing-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: